#!/bin/bash

if [ "x$2" != "x" ]; then
  exit
fi

BRANCH_NAME=$(git symbolic-ref -q HEAD)
BRANCH_NAME=${BRANCH_NAME##*/}

ASANA_TASK_ID=`echo $BRANCH_NAME | awk -F '-' '{print$1}'`

if [[ $ASANA_TASK_ID =~ ^-?[0-9]+$ ]]; then

  ASANA_LINK=`echo $BRANCH_NAME | awk -F '-' '{print"https://app.asana.com/0/"$1"/"$1}'`
  COMMIT_END="[$ASANA_TASK_ID]($ASANA_LINK)"

  # issue key matched from branch prefix, prepend to commit message
  TEMP=`mktemp /tmp/commitmsg-XXXXX`
  (echo;echo; echo "[$ASANA_TASK_ID]($ASANA_LINK)"; cat $1) > $TEMP
  cat $TEMP > $1
  rm $TEMP

fi
