#!/usr/bin/env zsh

declare -A color

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

SPACEBAR_HEIGHT=32
yabai -m config external_bar all:$SPACEBAR_HEIGHT:0

color[focused]="0xE02d74da"
color[normal]=""
color[preselect]="0xE02d74da"

# global settings
# global settings
config=(
  mouse_follows_focus          on
  focus_follows_mouse          off
  window_placement             second_child
  window_opacity               on
  window_shadow                float
  insert_feedback_color        0xaad75f5f
  split_ratio                  0.50
  auto_balance                 on
  mouse_modifier               fn
  mouse_action1                move
  mouse_action2                resize
)
# active_window_opacity        1.0
# normal_window_opacity        0.75
# window_opacity_duration      0.0
## Border around active window ##
# window_border               on
# window_border_width         4
# active_window_border_color  "${color[focused]}"
# normal_window_border_color  "${color[normal]}"
# insert_feedback_color       "${color[preselect]}"

yabai -m config ${config[@]}

# mission-control desktop labels
yabai -m space 1 --label browse
yabai -m space 2 --label terminal
yabai -m space 3 --label social
yabai -m space 4 --label docs
yabai -m space 5 --label slack

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   20

# float certain apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Docker Desktop$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Plexamp$" manage=off
yabai -m rule --add app="^Table Plus$" manage=off
yabai -m rule --add app="^Sonos$" manage=off
yabai -m rule --add app="^Find My$" manage=off
yabai -m rule --add app="^TablePlus$" manage=off

# fix to float for child windows
yabai -m rule --add app="^Twitter$" title="Media" manage=off
yabai -m rule --add app="^Finder$" title="Copy" manage=off

# open apps in their correct displays
yabai -m rule --add app="^Firefox*" space=browse
yabai -m rule --add app="*Chrome*" space=browse
yabai -m rule --add app="^Slack$" space=slack
yabai -m rule --add app="^Asana$" space=browse
yabai -m rule --add app="^kitty$" space=terminal
yabai -m rule --add app="^Twitter$" space=social
yabai -m rule --add app="^Safari$" space=docs


# S K E T C H Y B A R  E V E N T S
yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"
yabai -m signal --add event=display_added action="sketchybar --update"
yabai -m signal --add event=display_removed action="sketchybar --update"

# signals
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"

borders active_color=0xff00ff00 inactive_color=0xff494d64 width=5.0 &

echo "yabai configuration loaded.."
