#!/usr/bin/env zsh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

SPACEBAR_HEIGHT=$(sketchybar -m config height)
yabai -m config external_bar all:0:$SPACEBAR_HEIGHT

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.65
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# mission-control desktop labels
yabai -m space 1 --label sqm
yabai -m space 2 --label personal
yabai -m space 3 --label code
yabai -m space 4 --label terminal
yabai -m space 5 --label mail
yabai -m space 6 --label social

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  30
yabai -m config bottom_padding               10
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   10

# float certain apps
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Docker Desktop$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Authy Desktop$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Plexamp$" manage=off
yabai -m rule --add app="^Viscosity$" manage=off
yabai -m rule --add app="^Sequel Ace$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^Sonos$" manage=off
yabai -m rule --add app="^Find My$" manage=off

# fix to float for child windows
yabai -m rule --add app="^Sequel Ace$" title="^\(MySQL*" manage=off
yabai -m rule --add app="^Twitter$" title="Media" manage=off
yabai -m rule --add app="^Finder$" title="Copy" manage=off
yabai -m rule --add app="^Viscosity$" title="Viscosity - in-diskstation-2018" manage=off
yabai -m rule --add app="^Viscosity$" title="Viscosity - fl-diskstation-2018" manage=off

# open apps in their correct displays
yabai -m rule --add app="^Firefox*" space=personal
yabai -m rule --add app="^Slack$" space=sqm
yabai -m rule --add app="^Google Chrome$" space=sqm
yabai -m rule --add app="^Code$" space=code
yabai -m rule --add app="^Alacritty$" space=terminal
yabai -m rule --add app="^HEY$" space=mail
yabai -m rule --add app="^Twitter$" space=social
yabai -m rule --add app="^TweetDeck$" space=social

# S K E T C H Y B A R  E V E N T S
yabai -m signal --add event=window_focused action="sketchybar -m trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m trigger title_change &> /dev/null"

# signals
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"

echo "yabai configuration loaded.."
