POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_CONTEXT_TEMPLATE="%m"

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time aws docker_machine ram battery)
POWERLEVEL9K_TIME_FORMAT="%D{\uf017 %H:%M \uf073 %m/%d/%y}"
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='\u2570'$'\U2500\uf0da  '
